### ISSUE TITLE
world currency source

### ISSUE THREAD

**Issue by FLemon** [alexprengere/currencyconverter#13]
Hi, this is not really an issue of this tool.

but would be good to have advice/suggestion of where to get the currency file for a more completed currencies, i.e. to include currency AZN

**Comment by DarioHett** [comment]
I am currently working on detaching the tool from the ECB file and rather
make on-demand http requests to the respective source; ie ECB API. This in
turn would easily extend to various central banks and such an extended
range of currencies.

Implemented some of that on my own prior to that, have a look here:
https://github.com/DarioHett/centralbankdata
Quiet messy but hopefully you get an idea of the functionality.

Best,
Dario

Am 19.07.2018 13:17 schrieb "Jin Feng Xie" <notifications@github.com>:

Hi, this is not really an issue of this tool.

but would be good to have advice/suggestion of where to get the currency
file for a more completed currencies, i.e. to include currency AZN

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/alexprengere/currencyconverter/issues/13>, or mute the
thread

**Comment by alexprengere** [comment]
I have no knowledge of a free data source with all currencies. You can take a look at [xe.com](https://www.xe.com) for their APIs. Note that you can actually scrap their content, I recently discussed PR #12 which contains code to extract the rates this way.
