### ISSUE TITLE
Add another fall back (last known rate) in case of missing rate

### ISSUE THREAD

**Issue by ululh** [alexprengere/currencyconverter#20]
Hello
We would need a new feature : falling back to the last known rate (rather than linear interpolation) in case rate is missing

I started a simple implementation but before going further I would like to know if you would consider such a feature. From what I saw in a comment that was probably forgotten it was the original implementation of the fallback
Anyway you can see my proposal there :
https://github.com/ululh/currencyconverter/commit/b6118b351ddea1d25cfd00a746edc701cf2130d8
Ideally the current flag should be renamed but for backwards compatibility I only added a new one
Should you agree with the idea but disagree with the code please let me know any change you would like me to perform or provide advice on the implementation

**Comment by alexprengere** [comment]
I think this is a good idea 😉, and I am curious about the use case where you would prefer such a fallback. 

Also you are right regarding the flag name, I would rather have a flag `fallback_on_missing_rate_method` that would be `linear_interpolation` by default, and then we could easily add other methods without growing the number of flags.

Do you think you will always need to fallback on the last known rate? I could imagine doing a fallback on the closest known rate, or a fallback on the newest known rate, as alternate fallback methods.

Once this is clearer I will implement it, either cherry-picking your commit or directly on master.

**Comment by ululh** [comment]
Great, thanks a lot !
Requirement is from Treasury team at my company. Use case is that in case of monthly closure on a sunday, they can't wait until monday to get newest or closest rate.
I guess it could be interesting though for currencies, or currencies sources with many missing rates and with you implementation it's going to be easy to add if needed

I'll let you know when I have tested but from what I saw in the code there is little chance that this won't fulfill my need
Thanks again

**Comment by ululh** [comment]
Yes that works for me !
Then, during testing I ran into floating arithmetics problem : 111.16999999999999 instead of 111.17 
Did you ever consider using the decimal module ?
I'm going to look how to use it outside of the module but that would be nice to have built-in arithmetic rounding

**Comment by alexprengere** [comment]
So I pushed https://github.com/alexprengere/currencyconverter/commit/f912f21dca14b60a76486ec09eaa0354ba075d1a on master, which contains a bit more docs and tests, and I will now close this issue.

Regarding the decimal module, it was actually [fairly easy to implement](https://github.com/alexprengere/currencyconverter/commit/39e05471f295a88f92306d5faa9b0bbdbdb4cc3d). I added a `decimal` boolean option when creating the `CurrencyConverter` to switch to `decimal.Decimal` when parsing rates and computing conversions. This is not by default because performance takes a serious hit (parsing decimal is about 10-20 times slower than parsing floats, so the load time is about 15 seconds instead of 1 second on my machine). 

Thanks for those ideas! I will probably make a PyPI release soon with those changes. If you see anything not working please report the bugs 😉
